/** Language text */
export const lang = {
  code: "fr-FR",
  system: "Système",
  server_started: "a démarré le serveur",
  fetched_netatmo_data: "a récupéré les données de la station météo",
  refreshed_netatmo_token: "a rafrachit le token de récupération des données de la station météo",
  user_already_exists: "Cet utilisateur existe déjà",
  user_does_not_exist: "Cet utilisateur n'existe pas",
  user_created: "a été crée",
  user_deleted: "a été supprimé",
  user_password_updated: "a eu son mot de passe réinitalisé par ${actor}",
  user_roles_updated: "a été mis à jour par ${actor} avec les roles suivants: [${roles}]",
  login_failed: "Utilisateur ou mot de passe incorrect",
  history_hidden_username: "Un utilisateur",
  forbidden: "Action interdite",
  bad_request: "Requête invalide",
  action_does_not_exist: "Action inconnue",
  action_enabled: "a activé ${target}",
  action_disabled: "a désactivé ${target}",
  action_photo_taken: "a pris une photo",
  bad_duration: "Durée invalide",
  action_on: "a allumé ${target} pour ${duration}",
  action_off: "a éteint ${target}",
  action_off_auto: "a éteint automatiquement ${target} allumé par ${actor} après ${duration}",
  action_on_until: "Actif jusque",
  bad_dates: "Dates invalides",
  light: "les lumières",
  heat: "le chauffage",
  aeration: "l'aération",
  water: "l'arrosage",
  video: "la caméra",
  camera: "l'appareil photo",
  light_name: "Lumières",
  heat_name: "Chauffage",
  aeration_name: "Aération",
  water_name: "Arrosage",
  video_name: "Vidéo",
  camera_name: "Photo",
  temperature: "Température",
  humidity: "Humidité",
  co2: "CO2",
  pressure: "Pression atmosphérique",
  noise: "Bruit",
  rain: "Pluie",
  windstrength: "Vent",
  guststrength: "Rafales",
  logout: "Déconnexion",
  login: "Connexion",
  username: "Nom d'utilisateur",
  password: "Mot de passe",
  automated_handling: "Gestion automatisée",
  manual_handling: "Gestion manuelle",
  manual_start: "Démarrage manuel",
  manual_stop: "Arrêt manuel",
  action_manage: "Gérer cette action",
  enable: "Activer",
  disable: "Désactiver",
  "1m": "Pendant 1 minute",
  "5m": "Pendant 5 minutes",
  "10m": "Pendant 10 minutes",
  "15m": "Pendant 15 minutes",
  "30m": "Pendant 30 minutes",
  "1h": "Pendant 1 heure",
  "2h": "Pendant 2 heures",
  "3h": "Pendant 3 heures",
  "4h": "Pendant 4 heures",
  "5h": "Pendant 5 heures",
  "6h": "Pendant 6 heures",
  "7h": "Pendant 7 heures",
  "8h": "Pendant 8 heures",
  "9h": "Pendant 9 heures",
  "10h": "Pendant 10 heures",
  "11h": "Pendant 11 heures",
  "12h": "Pendant 12 heures",
  history: "Historique",
  history_entry_by: "Initié par",
  history_entry_action: "Action",
  history_entry_date: "Date",
  users_manage: "Gestion les utilisateurs",
  users_name: "Utilisateur",
  users_is_admin: "Administrateur",
  users_can_manage_users: "Gérer les utilisateurs",
  users_can_manage_actions: "Gérer les actionneurs",
  users_last_login: "Dernière connexion",
  users_never_logged: "Jamais connecté",
  users_actions: "Actions",
  edit: "Modifier",
  delete: "Supprimer",
  create: "Créer",
  change_password: "Changer le mot de passe",
  password_initial: "Mot de passe initial",
  password_new: "Nouveau mot de passe",
  password_confirm: "Confirmer le nouveau mot de passe",
  last_updated: "Mis à jour le",
  date_from: "De",
  date_to: "à",
}
